### ISSUE TITLE
Usernames are case sensitive

### ISSUE THREAD

**Issue by Gawen** [vdaubry/github-awards#1]
Hey,

Nice project :)

Tried to "github-awards" me but didn't work. My username is `gawen` but the page answers "User gawen not found".

As you see, I **do** exist ;-)

**Comment by vdaubry** [comment]
In fact your user is missing from the database, I will reimport your user and your repo and calculate the ranking again.

Thanks for reaching out !

**Comment by Moter8** [comment]
Seems that usernames are case sensitive. `moter8` returns this error and Moter8 does not.

**Comment by Gawen** [comment]
Indeed! It works with `Gawen`

**Comment by AustinDizzy** [comment]
In my case, neither AustinDizzy nor austindizzy work. Both return that the user is not found. To prevent this from happening to a larger range of users, if the user is not found on the first go it should check the live API to see if the user exists and add them accordingly if necessary.

**Comment by vdaubry** [comment]
Fixed, i'll deploy an update today
