### ISSUE TITLE
[suggest]have some public APIs?

### ISSUE THREAD

**Issue by awesomes-cn** [vdaubry/github-awards#102]
Hi,I want to know whether you provide APIs. I have a web app which focus on web development,and I want to get the rank data which language is javascript and location is each user's country and worldwide.So I want to get the data simply from your API and we will leave the link to your site just use something like 'see more ranks'.So do you have some  APIs,or I can get the data from other ways?Thanks!

**Comment by vdaubry** [comment]
There is a beta version of the Github Awards API 
Here is the documentation :

http://github-awards.com/docs

We're looking for feedback so please open an issue if you have any questions or if you find some bugs !

:warning: The API is still in beta and methods signature can change anytime :warning:
