### ISSUE TITLE
Double counting old repos

### ISSUE THREAD

**Issue by peter-edge** [vdaubry/github-awards#106]
I did a massive rename of my old repos recently, ie renaming from go-flights to flights-go, etc. My star count basically doubled, I was wondering what was going on but this seems like the logical answer. How is caching done?

**Comment by vdaubry** [comment]
Data are updated by reading [GitHub Archive](https://www.githubarchive.org/) hourly update.
I'm not sure how a name change event is reported.

There is no caching, data are calculated in real time using Redis Sorted Set, I advise you to manually refresh your profile to get latest data from the API.

Let me know if it fixes your problem.

**Comment by peter-edge** [comment]
I refreshed a number of times in the last week or so, it stays the same. I
know I do not have 154 stars for go, for example.

**Comment by peter-edge** [comment]
Any updates? Heh sorry :) Just wanted to make sure this was an issue.

**Comment by Mte90** [comment]
Same problem for me with the caching.
On my page http://github-awards.com/users/search?login=mte90 are reported some repo and languages that not exist anymore and with the refresh done in many months not change that.

**Comment by peter-edge** [comment]
I can work on repro steps, but my bet is that this would reproduce it:

- make a new user, alice
- make a new repo using alice, foo, with one .go file in it
- star that repo from your main user
- refresh Alice on github awards, should show 1 star
- rename foo to foo-go
- refresh Alice on github awards, I bet it will show 2 stars
- delete foo, create baz, one .go file, star baz from your main user
- refresh Alice on github awards, I bet it will show 3 stars
