### ISSUE TITLE
Can't fetch data for profile

### ISSUE THREAD

**Issue by kostiakoval** [vdaubry/github-awards#11]
http://github-awards.com/users/search?login=kostiakoval
I've renamed my account a month ago.
I can't see my town and country. I have public repos but they are not visible in ratings :(

**Comment by kostiakoval** [comment]
I have repose and many start
https://github.com/search?utf8=%E2%9C%93&q=fullname%3A%22Kostiantyn+Koval%22+user%3Akostiakoval&type=Repositories&ref=searchresults

Is there a way to refetch user account ?

**Comment by vdaubry** [comment]
I'm working on it, stay tuned.

**Comment by kostiakoval** [comment]
Sweet, thanks! @vdaubry

**Comment by matteocrippa** [comment]
Hey @vdaubry, I noticed that scraping my profile the script set me in Madagascar, it seems not to recognize Italy

**Comment by vdaubry** [comment]
I updated your locations. I'll update the ranking today
