### ISSUE TITLE
Does it count the organization repos?

### ISSUE THREAD

**Issue by greenlaw110** [vdaubry/github-awards#114]
The heaviest repos are in two organizations I've created, will they get counted?

**Comment by 3lvis** [comment]
Yes, github awards also takes in account organizations.

**Comment by greenlaw110** [comment]
perhaps I should rephrase my question, does it take count the person's commitment in organization repos into personal credential? The reason I as is I found my rank get down after I refreshed my profile because I moved some repos into organization repos

**Comment by 3lvis** [comment]
Oh, yeah, your stars get moved to the organization.

**Comment by greenlaw110** [comment]
I see. thanks

**Comment by JimBobSquarePants** [comment]
What's supposed to happen when you own an organization? 

E.g. I own this organization and [repo](https://github.com/ResponsiveBP)
Yet the stars are not associated with my [personal account](https://github.com/JimBobSquarePants).

http://git-awards.com/users/jimbobsquarepants
