### ISSUE TITLE
Bad geo-location

### ISSUE THREAD

**Issue by AD7six** [vdaubry/github-awards#13]
I took a look at the source, but couldn't see where it comes from.

I'm based in Spain, and [my github data reflects that](https://api.github.com/users/AD7six). However http://github-awards.com/users/AD7six shows the UK, which is quite confusing. I'm also, apparently [surrounded by Spaniards in East Hampshire](http://github-awards.com/users?city=east+hampshire&language=php&type=city)

Where is this location coming from?

**Comment by missinglink** [comment]
I'm 15th for Javascript for Ireland, woohoo!

**Comment by vdaubry** [comment]
Google map API can be used for bulk geocoding (limited to 2.500 calls / day)

To solve this problem part of the Geocoding was done with Openstreetmap API which turns to give quite poor results compared to Google map.

I updated your locations. I'll update the ranking today
