### ISSUE TITLE
"Warning! redirect_uri_mismatch" after revoke

### ISSUE THREAD

**Issue by item4** [vdaubry/github-awards#136]
I am not live in Kuala lumpur nor Malaysia.

I want to reload but I misclicked app revoke from GitHub.

I can not refresh info and can not re-login to git-award. :(

**Comment by item4** [comment]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/559952/21845807/72e50c94-d837-11e6-9b6b-cbb55428325c.png)

**Comment by rohmanhm** [comment]
got same problem

**Comment by vdaubry** [comment]
Thanks for reporting this. it should be fixed now
