### ISSUE TITLE
Please, delete this duplicate or not found users

### ISSUE THREAD

**Issue by SwiftCarlos** [vdaubry/github-awards#137]
Please, delete this duplicate or not found users from Barcelona and Spain Swift lists:

{"users":[{"id":16076167,"login":"cybercarlos","gravatar_url":"https://avatars.githubusercontent.com/u/8502419?v=3","city":"barcelona","country":"spain","stars_count":2934,"city_rank":1,"country_rank":1,"world_rank":105},{"id":16039262,"login":"carlosencoding","gravatar_url":"https://avatars.githubusercontent.com/u/8502419?v=3","city":"barcelona","country":"spain","stars_count":2890,"city_rank":2,"country_rank":2,"world_rank":107},{"id":12987990,"login":"cbutron","gravatar_url":"https://avatars.githubusercontent.com/u/8502419?v=3","city":"barcelona","country":"spain","stars_count":2781,"city_rank":3,"country_rank":3,"world_rank":110},{"id":15914774,"login":"carlbtrn","gravatar_url":"https://avatars.githubusercontent.com/u/22405563?v=3","city":"barcelona","country":"spain","stars_count":2639,"city_rank":4,"country_rank":4,"world_rank":121},{"id":15697213,"login":"carlbutron","gravatar_url":"https://avatars.githubusercontent.com/u/20501185?

**Comment by swiftcarlos** [comment]
I moved cybercarlos and carlosencoding to Marshal Island, but is impossible to change or update cbutron, carlbtrn or carlbutron

"id":16076167, "id":16039262, "id":12987990, "id":15697213 not found 404
"id":15914774 has 0 starts, but in your list have more than 2000....

Please fix it

**Comment by SwiftCarlos** [comment]
Fixed! :)
