### ISSUE TITLE
301 Redirect error? 

### ISSUE THREAD

**Issue by alvarotrigo** [vdaubry/github-awards#139]
I am calling the following URL from PHP using Curl:
http: //github-awards.com/api/v0/users/

And recently I started getting the following data:
```html
<head>< title > 301 Moved Permanently < /title></head > < body bgcolor = "white" > < center > < h1 > 301 Moved Permanently < /h1></center > < hr > < center > nginx / 1.6.2 < /center>
</body > < /html>
```

Did anything changed recently with the API ? If so, how can I avoid this issue?
Calling the same URL directly from the browser seems to work normally.

**Comment by vdaubry** [comment]
The website moved to http://git-awards.com/ , you should update your script.

**Comment by alvarotrigo** [comment]
Thanks for the quick answer! Awesome work here! Keep it up!
