### ISSUE TITLE
Re-collecting user data

### ISSUE THREAD

**Issue by keathley** [vdaubry/github-awards#15]
First of all I think this is a really cool project! :tada: 

I was wondering if it was possible to re-index geolocation data.  I added my location recently and its not present on the site.  Is there any way to re-index that data?

Thanks

**Comment by natzim** [comment]
:+1: for this. I set my location to UK, and it detected it as Russian Federation. Changed it now and still says Russian Federation.

**Comment by vdaubry** [comment]
I updated your location. Bulk geocoding is not easy because of rate limiting. I need to work on a better solution for this

**Comment by vdaubry** [comment]
Important note : I'll update the ranking today, it's not online yet

**Comment by keathley** [comment]
Thanks for taking care of this :+1:

**Comment by juliangruber** [comment]
can you please update mine as well?

**Comment by vdaubry** [comment]
You have an update button under your avatar picture now, it should take no more than a few minutes

**Comment by juliangruber** [comment]
thanks, worked perfectly :)
