### ISSUE TITLE
List out of order and missing ranks

### ISSUE THREAD

**Issue by ranisalt** [vdaubry/github-awards#155]
The page for top C++ developers in my city ([here](http://git-awards.com/users?utf8=%E2%9C%93&type=city&language=c%2B%2B&city=florian%C3%B3polis)) is out of order and a lot of rank numbers are missing.

**Comment by oprogramador** [comment]
@ranisalt 

could you close this issue and like (👍) https://github.com/vdaubry/github-awards/issues/153 which is the same but has more likes?

**Comment by ranisalt** [comment]
Sure!
