### ISSUE TITLE
Russia and Russian federation must be same country.

### ISSUE THREAD

**Issue by proofit404** [vdaubry/github-awards#16]
Also there is the same bug with russian cities `Nizhniy novgorod` and `Nizhny novgorod`.

P.S. Thanks for this project. Awesome idea!

**Comment by vdaubry** [comment]
Thanks it's fixed.
I'll update the ranking today

**Comment by proofit404** [comment]
Thanks!

**Comment by proofit404** [comment]
Actually this issue still present both for Russia country and for Nizhniy novgorod city.
