### ISSUE TITLE
City not updating

### ISSUE THREAD

**Issue by brean** [vdaubry/github-awards#168]
Hi, 

some time ago I moved to Wuppertal and changed it in my github account, but github-awards is not updating, it still shows "Mülheim" as my city. (see http://git-awards.com/users/search?login=brean )

- Andreas

**Comment by brean** [comment]
Today it is updated... interesting, do I have to manually click the "update profile" button when I move or did someone here updated it manually?

**Comment by johnmcfarlane** [comment]
I haven't lived in Seattle for years and no longer live in the US [but I'm ranked that way](http://git-awards.com/users/search?login=johnmcfarlane). Goodness knows where it's picking the information up from.

**Comment by oprogramador** [comment]
@brean 

could you close this issue and like (👍) https://github.com/vdaubry/github-awards/issues/153 which is very similar but has more likes?
you could write your exact situation in a comment

**Comment by brean** [comment]
closed, duplicate of #153

**Comment by johnmcfarlane** [comment]
@brean @oprogramador This issue was not a duplicate. It tracks the wrong location being used. #153 tracks failure to determine any location at all.

I am not experiencing the problem tracked by #153 and have no plans to +1 it.
