### ISSUE TITLE
Refresh data is not working

### ISSUE THREAD

**Issue by wellingtoncosta** [vdaubry/github-awards#170]
I tried to update my data by clicking in the green button, but it sounds not working. Currently, my city location is not appearing, but I have this information on my GitHub account.

**Comment by diegohaz** [comment]
Not sure if it's related, but it's been a few days (or a week) since numbers aren't updated automatically.

**Comment by WellingtonCosta** [comment]
One week went by and my data wasn't updated. :(

**Comment by diegohaz** [comment]
Any idea, @vdaubry?

**Comment by WellingtonCosta** [comment]
@brean has mentioned in issue #168 that his city information was updated after 29 days "mysteriously".

**Comment by brean** [comment]
@WellingtonCosta I think there might be either some human involved because it updated "mysteriously" one day after I created the issue on github 😉 or the update-process takes at least a day after you click on "Refresh your profile".

**Comment by antonioribeiro** [comment]
Around zero updates in the last 20 days or so in this page: http://git-awards.com/users?country=brazil&language=php, even manually updating my profile does nothing.

**Comment by bruno-alencar** [comment]
Hey, my ranking is not updating and not requesting for refresh.

**Comment by wellingtoncosta** [comment]
No answer from @vdaubry ...

**Comment by bruno-alencar** [comment]
Do we have to ask him on twitter?

**Comment by bruno-alencar** [comment]
Do we have to ask him on twitter?

**Comment by mtojek** [comment]
@vdaubry +1

Is there any support for this feature? Maybe somebody from OSS can deliver it.

**Comment by YagoAzevedo** [comment]
I have the same problem. After updating my city in github account and refresh my info's in git awards, my city still empty.

**Comment by Vali0** [comment]
Same issue here, I've been waiting for a month already and my city is still missing. Does anyone have an idea who we can contact or how to resolve this problem?

**Comment by Niyiojeyinka** [comment]
same issue here

**Comment by hasanmoha** [comment]
hello

**Comment by Hamza-Dahmoun** [comment]
same issue here, it's been three dates since I clicked on Refresh button but nothing is updated. the 'Refresh' button is disappeared now.

**Comment by wellingtoncosta** [comment]
It looks like the author left the project out, so I'm closing this issue.
