### ISSUE TITLE
 Why can't I see my city rankings?

### ISSUE THREAD

**Issue by nanchen2251** [vdaubry/github-awards#189]
I saw the same problem，but how to solve。

android my name is nanchen2251.

in Chengdu

**Comment by nanchen2251** [comment]
![image](https://user-images.githubusercontent.com/15808532/57520149-886d8400-734f-11e9-89ea-da5ecb07897a.png)
![image](https://user-images.githubusercontent.com/15808532/57520262-cb2f5c00-734f-11e9-9ba2-e39ab2e9f31c.png)

**Comment by wuriyanto48** [comment]
same problem here

**Comment by KunMinX** [comment]
me too.

Hangzhou, China

**Comment by shamim0902** [comment]
I also can't see my country and city location.
username:  hasanuzzamanbe

**Comment by librauee** [comment]
same problem here.
Zhoushan

**Comment by oprogramador** [comment]
@nanchen2251 

could you close this issue and like (👍) https://github.com/vdaubry/github-awards/issues/153 which is the same but has more likes?

**Comment by nanchen2251** [comment]
> @nanchen2251
> 
> could you close this issue and like (👍) #153 which is the same but has more likes?

ok. thanks
