### ISSUE TITLE
Branding and naming goes against GitHub's policies

### ISSUE THREAD

**Issue by lukeb-uk** [vdaubry/github-awards#20]
GitHub Awards has been confused as an actual GitHub project. GitHub explicitly ask that you avoid naming projects anything that makes it seem like an endorsement:

> ### Naming projects and products
> 
> Please avoid naming your projects anything that implies GitHub’s endorsement. This also applies to domain names.

The background for the site also seems to be a modified version of the Octocat, which is again against their policies:

> ### Please don’t do these things
> 
> Create a modified version of the Octocat or GitHub logo

Whilst GitHub Awards does describe what the project does, I feel that it needs to be renamed or it may be closed down by GitHub.

Source: https://github.com/logos

**Comment by vdaubry** [comment]
Thanks for raising this issue. I actually tried to reach GitHub without success.
Renaming the project would be the worst solution. If GitHub is worried about the branding i would love to address this issue with them and figure out a proper solution.

Untill then I will make the statement in the footer larger : "This project is not affiliated with the GitHub company in any way."

Regarding the logo : the background is using [octicons](https://github.com/github/octicons)

**Comment by lukeb-uk** [comment]
Adding a footer does not address the fact that your project breaks their policies in terms of naming, especially when the footer is below the visible screen space on a 1366x768 screen (most popular screen size according to http://gs.statcounter.com/#resolution-ww-monthly-201411-201501).

**Comment by jeremykendall** [comment]
I love this project, a lot, but I have to agree with @lukeb-uk. The name should be changed posthaste. A name change won't kill a great project (see [Aura PHP](http://auraphp.com/about) [name changed from Solr to Aura] and [Common Markdown](http://blog.codinghorror.com/standard-markdown-is-now-common-markdown/)). I would *hate* to see this get shut down over naming conflicts and ToS violations.

FWIW, I have a small amount of reach in the PHP community, especially on Twitter. I'd be happy to help market a name change with the little bit of reach that I have.

**Comment by vdaubry** [comment]
You have a point. I tried to reach GitHub without success, ultimately it's their decision. Untill then, i'm closing this issue now.
