### ISSUE TITLE
Some users are missing

### ISSUE THREAD

**Issue by miguelgrinberg** [vdaubry/github-awards#25]
I can't find myself in the search.

**Comment by h6ah4i** [comment]
Yeah, I cannot find my account too.

**Comment by lavary** [comment]
If you're testing on your smart phone, make sure you username isn't capitalized. Apparently the search is case sensitive.

**Comment by miguelgrinberg** [comment]
Yeah, this is not a case sensitive issue, at least not for me.

**Comment by vdaubry** [comment]
The case sensitive search bug is fixed. Your 2 users are missing from the DB, probably a problem related to github-archive dataset.
I'm working on adding a real-time update with github connect and a refresh button, that should solve these issues.
