### ISSUE TITLE
Duplicate users displayed in rankings

### ISSUE THREAD

**Issue by jessesquires** [vdaubry/github-awards#26]
URL after tapping "submit"
http://github-awards.com/users?utf8=✓&type=city&language=objective-c&city=San+francisco

The unicode (checkmark) breaks on Twitter. Thus, removing it:

http://github-awards.com/users?type=city&language=objective-c&city=San+francisco

This URL works, but now shows duplicates for each user.

**Comment by jeremykendall** [comment]
I'm seeing a lot of duplication as well. Here's a screenshot of what I'm currently seeing on the [Top Php GitHub developers in Memphis](http://github-awards.com/users?city=memphis&language=php&type=city) page.

![screenshot 2015-03-01 10 44 27](https://cloud.githubusercontent.com/assets/288613/6431749/13417e36-c000-11e4-8998-4c6ac719c45e.png)

Somewhat related: The #1 PHP dev in Memphis, TN is actually located in the state of Nebraska. See [my comment](https://github.com/vdaubry/github-awards/issues/2#issuecomment-76610862) on #2.

**Comment by vdaubry** [comment]
Sorry about that, i'm in the process of moving to another host and there was a DB problem. It's fixed now
