### ISSUE TITLE
Can't find my city

### ISSUE THREAD

**Issue by technion** [vdaubry/github-awards#27]
Hi,

At first I thought this was because my Github location was "Australia" but I've updated it to refer to a city, and several days later this tool still claims it can't find my city, and goes on to present some defaults? for a search of Cuba.

**Comment by vdaubry** [comment]
Update are not automated yet, i'm working on it stay tuned.

**Comment by dkvasnicka** [comment]
Do you think you could reopen this issue and close it when this is addressed so that we can "stay tuned" and be notified when it's done? ;)
Keep up the good job!
