### ISSUE TITLE
Does not work with login with capital letters

### ISSUE THREAD

**Issue by GCorbel** [vdaubry/github-awards#29]
As you can see in my page : http://github-awards.com/users/search?login=GCorbel. There is no result right now. It worked on 27-02-2015.

Thanks!

**Comment by Inferis** [comment]
Same here :)

**Comment by GCorbel** [comment]
I think it's because we have a capital letter in our name.

**Comment by Trii** [comment]
Me neither. There is a bug with uppercase letters

http://github-awards.com/users/search?login=Trii

**Comment by TaylorKolasinski** [comment]
Looks like in the following commit, they started downcasing usernames for search:

https://github.com/vdaubry/github-awards/commit/7488e4a733fe2da0f728dfc1920e6795ab7394b1

**Comment by GCorbel** [comment]
@TaylorKolasinski, I think you're right. All usernames, in the database, have to be change for downcase.

**Comment by Parkayun** [comment]
Same here, too.

**Comment by RaVbaker** [comment]
@vdaubry please fix it!

**Comment by Gawen** [comment]
Same here.

**Comment by vdaubry** [comment]
Hi everyone,

There was a case issue when uploading latest events from GitHub Archive last week end.
I'm currently switching to a real time ranking with Redis instead of a huge batch ranking with Postgres. In this process it will also solve references between users and repo.
I hope to get this in production by the end of next week.

Thanks again for your support and your patience ;)

Vincent

**Comment by andersennl** [comment]
I can't find myself neither (I never could). Yesterday I corrected my location in the settings. I used my country before, now it's the name of my city.

**Comment by LuizCarvalho** [comment]
Still no solution?

**Comment by Tonkpils** [comment]
@LuizCarvalho I believe the solution is being worked on. I'm assuming https://github.com/vdaubry/github-awards/pull/39 will fix this issue once its finished. @vdaubry If there's anything we can do to help this move along let us know! :+1:

**Comment by LuizCarvalho** [comment]
Oh great! Thanks @Tonkpils  and @vdaubry  :D

**Comment by vdaubry** [comment]
Problem fixed, i'm closing this issue now.

**Comment by Inferis** [comment]
\o/

**Comment by Mazyod** [comment]
:dancers:
