### ISSUE TITLE
Some repositories are missing

### ISSUE THREAD

**Issue by kostiakoval** [vdaubry/github-awards#32]
For example:
I have 6 swift repositories (my own sourced repos)
https://github.com/kostiakoval?tab=repositories
But in report it says only 1
http://github-awards.com/users/kostiakoval

Those repos are few months old, (if you refetched data, they should appear in awards status)
I've seen this for other users too

**Comment by vdaubry** [comment]
Repositories data are coming from github archive, they recently changed the way they store events. Anyway i will add a refresh buttons that will allow your to manually ask for a refresh.

**Comment by mitulgolakiya** [comment]
:+1: for manually refresh. Even I have 4-5 repositories for PHP but it only displays 2 Repo.

**Comment by vdaubry** [comment]
Hello, i added a refresh button, can you try to go on your profil and run an update ?

**Comment by mitulgolakiya** [comment]
Yes, it seems working now.

Thanks @vdaubry.
