### ISSUE TITLE
Problems with PowerShell language report

### ISSUE THREAD

**Issue by vors** [vdaubry/github-awards#33]
![image](https://cloud.githubusercontent.com/assets/816680/6477042/d105f644-c1d2-11e4-8759-1fb37924928c.png)

Problems are probably related:
1. PowerShell listed more then once (4+ times) in language list
2. Rank is less then total number of people for a few ratings.

**Comment by vdaubry** [comment]
Thanks i'm working on adding real time ranking, it will also solve this issue.
