### ISSUE TITLE
China and PRC are not considered the same

### ISSUE THREAD

**Issue by riophae** [vdaubry/github-awards#36]
http://github-awards.com/users/turingou (China 1 / 2 642)
http://github-awards.com/users/nswbmw (People's republic of china 7 / 7 200)
Both users are Chinese. But they were ranked in different country lists.

**Comment by tobegit3hub** [comment]
We should fix it before some radical people take it seriously :bow:

**Comment by riophae** [comment]
I'm sorry I'm not good in English... May be a bit misleading :)
Just wish all Chinese could be ranked in one list (by programing language).

**Comment by vdaubry** [comment]
Thanks i'll fix geocoding for people from China.

**Comment by weakish** [comment]
China and PRC are not the same.

Both governments of China and PRC claims they stand for *the country*.
But this is a political issue.

Technically, China and PRC uses different country/region code: China uses `CN` and PRC uses `TW`.
Most software systems separate  locales between 'zh_CN' and 'zh_TW'.
So maybe this is not a bug.

**Comment by riophae** [comment]
China and PRC are just the same, differing from ROC.
The last uses `zh_TW` and others use `zh_CN`.

FYI:
http://www.wikiwand.com/en/China
http://www.wikiwand.com/en/Taiwan

**Comment by weakish** [comment]
@riophae  Sorry I made a mistake.

**Comment by riophae** [comment]
@weakish Never mind :)

**Comment by vdaubry** [comment]
Hi everyone, it's fixed and a brand new version of github awards with github connect and a blazing fast new hosting :)

Can you try and tell me if it works for you ?

**Comment by riophae** [comment]
WOW! It works perfectly for me. `China`, `Mainland China`, `Peking`, `Beijing` are all handled properly.
Sorry to say that I've looked around for `People's Republic of China` for a long time but nobody found... Can't validate that for you.

BTW, hope you are not bothered by the ugly avatars of those guys... Very smart people tend to be weird and tasteless, right? ;)

**Comment by tobegit3hub** [comment]
Nice work @vdaubry :+1:
