### ISSUE TITLE
Problems with user's country

### ISSUE THREAD

**Issue by si14** [vdaubry/github-awards#4]
Here is an example:

https://github.com/mikera
http://github-awards.com/users/mikera

![screenshot from 2015-02-26 18 55 49](https://cloud.githubusercontent.com/assets/316910/6395430/22caeaf4-bde9-11e4-8eb8-5c48ee6f67d2.png)

![screenshot from 2015-02-26 18 55 59](https://cloud.githubusercontent.com/assets/316910/6395431/22cf0922-bde9-11e4-8664-2350f19d3288.png)

**Comment by vdaubry** [comment]
Yep, I had to geocode most location with Openstreetmap which is far less accurate than Google Maps API.
I'll gecode the corresponding profile again

**Comment by pfefferle** [comment]
Same for my profile:

https://github.com/pfefferle

**Comment by sirwolfgang** [comment]
It says I am in the philippines, rather then `United States`

**Comment by gkcgautam** [comment]
It shows Serbia as my country, although I have mentioned Mumbai, India in my profile :(

**Comment by scottrblock** [comment]
Keeps showing me in the Philippines too, rather than United States.

**Comment by FlexMonkey** [comment]
Would you mind looking at my geocode?

https://github.com/FlexMonkey

**Comment by qidane** [comment]
My github profile has "St Andrew, Scotland" entered, but award site is showing me as "Chambersburg, United states"

**Comment by ncw** [comment]
[Mine](http://github-awards.com/users/search?login=ncw) has "Russian federation" for "UK" in my github profile.  I changed my location to "Guildford, UK" in the hope it might improve!

**Comment by whackashoe** [comment]
Mine also says Philippines; I am in US

**Comment by barryvdh** [comment]
Perhaps also related, my country is 'the Netherlands', but it also occurs as just Netherlands..

**Comment by andres-root** [comment]
Same in my profile, no matter how I write the city name, it never can get my city. https://github.com/andres-root

**Comment by lavary** [comment]
Mine also says Spain but I'm in Iran

**Comment by vdaubry** [comment]
I'm working on fixing locations now, i will update ranking today. Thanks for your patience

**Comment by vdaubry** [comment]
Locations are fixed, you'll see your updated profile when the ranking calcultation is finished

**Comment by pfefferle** [comment]
I am still located at the Philippines...

**Comment by gkcgautam** [comment]
@vdaubry Still displays Serbia for me.

**Comment by vdaubry** [comment]
That's what i said : "you'll see your updated profile when the ranking calcultation is finished" ;)

**Comment by pfefferle** [comment]
Ah ok, sorry and thanks 😉

**Comment by mcustiel** [comment]
Hi. I see this is supposed to be fixed but I'm still seeing my location as Buenos Aires, Argentina when my contributions were made from Montevideo, Uruguay. Thanks.

**Comment by vdaubry** [comment]
@mcustiel Can you try to update your profile again ? (button "refresh your profile" under your avatar)

**Comment by mcustiel** [comment]
@vdaubry Done.

**Comment by vdaubry** [comment]
Ok i fixed your location

**Comment by mcustiel** [comment]
Great! Thank you.
