### ISSUE TITLE
My profile is found but incorrect

### ISSUE THREAD

**Issue by GuillaumeGomez** [vdaubry/github-awards#40]
Hi,

My profile is found and I'm located in the United States (???) while my profile says I'm in Paris. So I have no data on it.

**Comment by vdaubry** [comment]
Hi, i added an update button in the profil page, can you try to refresh ?

**Comment by GuillaumeGomez** [comment]
Thanks, it's working now ! Only one problem remains: it doesn't find my city (which is filled as Paris on github). Otherwise, everything's fine !

**Comment by vdaubry** [comment]
Google geocoding may take a few second to run (more if your refresh is in queue behind others)

When i go to your profile you're listed in Paris, i think it's ok.

**Comment by GuillaumeGomez** [comment]
Perfect then ! Thanks again for fixing it.
