### ISSUE TITLE
My profile is empty

### ISSUE THREAD

**Issue by Kevnz** [vdaubry/github-awards#41]
My profile kevnz is blank with no information at all. This despite the following stats I was able to gather from github api
My repo counts
JavaScript: 278,
  null: 47,
  'C#': 15,
  Ruby: 7,
  CoffeeScript: 3,
  CSS: 10,
  ASP: 1,
  ActionScript: 1,
  Python: 3,
  HTML: 4,
  C: 2,
  Perl: 1,
  LiveScript: 1,
  PowerShell: 1,
  Java: 2,
  'Objective-C': 3,
  'C++': 4

 and my stars per repo

JavaScript: 136,
  null: 4,
  'C#': 3,
  Ruby: 5,
  CoffeeScript: 2,
  CSS: 4,
  ASP: 0,
  ActionScript: 0,
  Python: 2,
  HTML: 2,
  C: 1,
  Perl: 0,
  LiveScript: 0,
  PowerShell: 0,
  Java: 0,
  'Objective-C': 1,
  'C++': 3

Maybe the null returns are a problem?

**Comment by Mazyod** [comment]
+1

**Comment by Tonkpils** [comment]
Duplicate of https://github.com/vdaubry/github-awards/issues/29

**Comment by RobertWHurst** [comment]
+1

**Comment by vdaubry** [comment]
Hi, i added a refresh button on the profile page. You can update your profile and check that stats are ok ?

**Comment by RobertWHurst** [comment]
Looks good! Nice work @vdaubry :beers:
