### ISSUE TITLE
My account can't be found

### ISSUE THREAD

**Issue by andersennl** [vdaubry/github-awards#43]
Maybe because I used to have "Germany / Denmark" in my location field? I recently changed it to the city I'm currently living in. Thanks :)

**Comment by RobertWHurst** [comment]
My profile also cannot be found. I don't think its because of location.

**Comment by dciccale** [comment]
My location is not being recognized, I updated it but the website doesn't seem to care

**Comment by bugalot** [comment]
Mine cannot be found either. Maybe because I recently changed my user name?
Thanks for this great project!

**Comment by vdaubry** [comment]
Hi everyone, you can now go to your profile page and run a refresh. Tell me if it works for you after that.

**Comment by bugalot** [comment]
Hello Vincent! Still no joy for me after a refresh.
Cheers

**Comment by dciccale** [comment]
Is working for me, and now I can see a button to update and it works also, thanks!

**Comment by vdaubry** [comment]
@bugalot i guess it was just a delay in the background process, i can see your profile now : http://www.github-awards.com/users/search?login=bugalot

Seems to work then, i'm closing this issue.
