### ISSUE TITLE
stars number is not correct

### ISSUE THREAD

**Issue by metrue** [vdaubry/github-awards#44]
take my account for instance.

https://github.com/metrue?tab=repositories

Stars on Ruby are more that 5
Objective C more 2
Javascript stars are more that 0.
but you can see:
http://github-awards.com/users/search?login=metrue

**Comment by vdaubry** [comment]
Hi, you can go to your profile and run a manual refresh, it should fix this.

**Comment by metrue** [comment]
@vdaubry 

right, issue closed.
