### ISSUE TITLE
Number of stars is incorrect

### ISSUE THREAD

**Issue by Inferis** [vdaubry/github-awards#48]
The reporting on the number of star is incorrect. According to Github Awards I have 3577 stars for Objective-C:

![](http://c.inferis.org/image/1a1J0T1J3a1T/Image%202015-04-02%20at%2011.13.22%20pm.png)

But my most popular repo, ViewDeck, alone has 4200+ stars:

![](http://c.inferis.org/image/0p1U311l2U3s/Image%202015-04-02%20at%2011.14.34%20pm.png)

So that can't be right (and I did not gain 700+ overnight or even overweek, so it's not a "just wait for the cache to be updated" issue, I think).

Any ideas?

**Comment by vdaubry** [comment]
To get an accurate number of stars did you try to manually update your account ? (you should see a 'Refresh your profile' button under your picture)

Number of star may not be up to date at the moment : data comes from [Github Archive](https://www.githubarchive.org/), they recently changed their format so it broke the import. I'm working on it.

**Comment by Inferis** [comment]
Yes, tried that. No effect.

Well, it's no biggie, but I thought I'd report it.

**Comment by vdaubry** [comment]
There was a pagination issue when updating a user with lots of repos.
To solve this issue I need to implement pagination of Github API responses.

In the meantime i added a quick fix to get the 100 first repos of each user (which covers 99.99% of github users) , it should solve your problem.

Can you try again ?

**Comment by Inferis** [comment]
That works! Thanks!
