### ISSUE TITLE
Still can not find my profile

### ISSUE THREAD

**Issue by Cee** [vdaubry/github-awards#49]
When I press the refresh button and redirect to the github-awards page, I meet an error saying that `We're sorry, but something went wrong.` . Would you please check the log file and fix this problem?

**Comment by vdaubry** [comment]
Thanks for reporting this bug. It seems there was a race condition when updating your profile. I fixed it, can you try again ?

**Comment by Cee** [comment]
There is a warning: Warning! Your accound could not be updated, please try again.

**Comment by vdaubry** [comment]
That's weird, i'm seeing 2 simultaneous requests comming from your ip, that's causing the race condition.

I changed the code to try to force an update in that case. Can you try again ?

**Comment by Cee** [comment]
OK. It's fine now. Thanks a lot!
