### ISSUE TITLE
Seems that the ranking charts dont update?

### ISSUE THREAD

**Issue by wesleytodd** [vdaubry/github-awards#53]
I am unfortunately not a rubyist, or this would come in the form of a PR instead of an issue.  But it seems that despite the new ability to update your user data, the rankings for a region do not update.  Seems to me like that would be an good addition, maybe just reshuffle that data when a user that exists in it updates their profile?

**Comment by vdaubry** [comment]
There is definetly a problem here, it might come from Redis sorted sets not updating properly while repository info in postgres are correct. I'm looking into this.

Thanks for notifying this issue.

**Comment by wesleytodd** [comment]
No problem!!  Sorry I can't help more.

**Comment by vdaubry** [comment]
Ok i fixed the problem and started a bulk update for rankings. I'll close this issue it when the update is finished.

**Comment by wesleytodd** [comment]
Awesome!!  Thanks for the fun site, hopefully you are getting some :dollar: for your hard work!!

**Comment by vdaubry** [comment]
Loggly has been awesome and is sponsoring the project, it's not much cash but it pays for hosting :)

Rankings are up to date, i'm closing this issue.

**Comment by Sottti** [comment]
Looks like this is happening again.

**Comment by vdaubry** [comment]
Background jobs were crashed and unable to restart, it's fixed now.

All profile will update automatically next time they appear in Github events timeline.
You can run a refresh on your profile if you don't want to wait.
