### ISSUE TITLE
Unable to refresh project

### ISSUE THREAD

**Issue by igorspasic** [vdaubry/github-awards#55]
How can I refresh organization page in github-awards: [oblac](http://github-awards.com/users/search?login=oblac)? Only my profile gets refreshed, but not organization?

With great fun comes great responsibility :) Please make it work, some serious bet is in place ;)))

**Comment by vdaubry** [comment]
The refresh occurs when your organiezation appears in Github Archive daily feed, if you make a commit, pull request, or comment it should be enough.

Let me know if it works ?

**Comment by igorspasic** [comment]
Ok. I've added a comment and bug was closed. I have also added a commit to the repo. Last change to the repo is 9 hours ago from this moment.

However, the geo-location information of the organization is not changed (it was missing before, and I would like to set it).

**Comment by igorspasic** [comment]
Apparently, stars count is re-freshed, but not the geo-location.

**Comment by vdaubry** [comment]
I updated your organisation location, it should be ok now.

**Comment by igorspasic** [comment]
Thanx, sorry for the all trouble.

**Comment by gep13** [comment]
@vdaubry is there any chance that you can do the same as you did for @igorspasic on the cake-contrib organisation? Thanks!
