### ISSUE TITLE
Stars per language may be wildly inaccurate.

### ISSUE THREAD

**Issue by benjamincharity** [vdaubry/github-awards#6]
First off, this is a really cool project!

I did notice that in some cases the ranking seems to be completely wrong...

If you look up who the top Atlanta based users in CSS are, user Alindeman is miles ahead of everyone else. But when you dive it to see _why_that is, there is only one CSS based repo with any stars at all and that repo has nothing to do with CSS at all: [upgradingtorails4](https://github.com/alindeman/upgradingtorails4)

Maybe someone with more knowledge of how GitHub determines the primary languages can chime in here. I see that GitHub marks the repo in question as over 97% CSS:

![screen shot 2015-02-26 at 1 34 13 pm](https://cloud.githubusercontent.com/assets/270193/6398839/63e6cdd2-bdbc-11e4-9c5e-d20d276d2ace.png)

But looking at the files themselves, there are only 5 (very minimal) CSS files:

![screen shot 2015-02-26 at 1 33 55 pm](https://cloud.githubusercontent.com/assets/270193/6398859/8c6b46c0-bdbc-11e4-94a6-9b0599ea385e.png)

It seems that even if GitHub didn't take Markdown into consideration, Ruby should still be considered the Repo's primary language.

I only checked the top 3 CSS contributors in Atlanta, but all of them seemed to be suffering from the same issue.

I don't have any brilliant solution to offer at the moment.. but I thought it was worth starting a discussion.

**Comment by vdaubry** [comment]
Github language detection is based on [linguist](https://github.com/github/linguist) library

It seems most files from this repo are considered markup files and excluded from language statistics : markdown, html, yml

This discussion explains why HTML files are excluded : https://github.com/github/linguist/issues/1019

There isn't really any ruby file in this repo (there is a helper.rb but all lines are comments).

The only files that are considered to be code on this repo seems to be CSS files, i wouldn't consider it a bug.

You can open an issue on the Linguist repo if you think this repo is in the wrong language. It's the recommended approach : https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/

**Comment by vdaubry** [comment]
Closing this issue now
