### ISSUE TITLE
Separate ranking for organizations versus users

### ISSUE THREAD

**Issue by caarmen** [vdaubry/github-awards#60]
Would like to see separate rankings for organizations versus users. 

Organizations often have multiple users contributing to their repositories.  At the risk of sounding like a whiner, it's not "fair" to compare organizations with a large number of contributors, to independent developers.

**Comment by caarmen** [comment]
![815833](https://cloud.githubusercontent.com/assets/1731388/8765319/cd05a33c-2e06-11e5-8867-ab4cac3dc123.jpg)

**Comment by vdaubry** [comment]
Thanks for this suggestion. I don't have a clear roadmap for this at the moment. I'll re-open this issue when i start working on this.

PR are welcome ;)
