### ISSUE TITLE
Organisation Location, not imported.

### ISSUE THREAD

**Issue by davideme** [vdaubry/github-awards#62]
I get the message "We couldn't find your city from your location on GitHub" for my organisation.
http://github-awards.com/users/karumi

But it's set as "Madrid, Spain" on https://github.com/karumi, is this correct and it's not parsed or it's expecting another format of location ?

Or it's simply cached and not invalidated, It's was updated more than a week ago.

**Comment by vdaubry** [comment]
Background jobs were crashed and unable to restart, it's fixed now.

Your location is up to date now.
