### ISSUE TITLE
Stars missing since 2 days

### ISSUE THREAD

**Issue by seiflotfy** [vdaubry/github-awards#64]
Great great great job on the github-awards. We have some bets here going on (or a competition) and sadly github-awards hasn't updated my profile and a teammates profile for 2 days or so. I know the missing stars is a github-archives issue, but is there a way you can help us out fixing it?
Cheers

**Comment by vdaubry** [comment]
Thanks !

Background jobs were crashed and unable to restart, it's fixed now.

All profile will update automatically next time they appear in Github events timeline.
You can run a refresh on your profile if you don't want to wait.
