### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by LyndonChin** [vdaubry/github-awards#66]
Thank you for your awesome project., but the data has not been updated for days.

**Comment by vdaubry** [comment]
Thanks, glad you like this project :)

Background jobs were crashed and unable to restart, it's fixed now.

All profile will update automatically next time they appear in Github events timeline.
You can run a refresh on your profile if you don't want to wait.

**Comment by ashleymills** [comment]
I'm guessing this has happened again - doesn't seem to have been updated for a day or 2

Cheers
Ash

**Comment by vdaubry** [comment]
@ashleymills Yes the backgound worker was down. Can you check again ?

**Comment by ashleymills** [comment]
Working like a charm! Thanks for your work on this, much appreciated.

Cheers
Ash

**Comment by ashleymills** [comment]
Seems like the background worker is down again

Ash

**Comment by vdaubry** [comment]
You're right, i restarted Sidekiq.

The sidekiq process is managed by Monit, but sidekiq was still stop and not restarted.
That's weird, i'm looking to understand what happened.

**Comment by ashleymills** [comment]
Looks like it's down again

Ash

**Comment by vdaubry** [comment]
@ashleymills : It's up, what makes you say that ?

**Comment by ashleymills** [comment]
I should have 1240 Swift, it's been showing only 1233 for a couple of days.

**Comment by vdaubry** [comment]
Did you force a refresh on your profile ?

On Sunday, 15 November 2015, Ashley Mills <notifications@github.com> wrote:

> I should have 1240 Swift, it's been showing only 1233 for a couple of days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vdaubry/github-awards/issues/66#issuecomment-156844453>
> .
>


-- 
Vincent Daubry
tel: 06 51 50 21 73
Twitter: @vdaubry

**Comment by ashleymills** [comment]
Yes, tried that a couple of times.

**Comment by vdaubry** [comment]
@ashleymills : Github API token was rate limited. Your account is now updated.
