### ISSUE TITLE
[Feature request] Link to user repositories on the specific language

### ISSUE THREAD

**Issue by marceloboeira** [vdaubry/github-awards#68]
It would be nice to have a link to github with a list of the users repositories on that specific listed language. Places like the ranking of the language, or the user profile.

### Example

![example](https://cloud.githubusercontent.com/assets/1898225/10209685/7e53189a-67b4-11e5-8341-f3d7ae16d242.png)

### Suggestion
Github provide a simple way to generate this link, just using their "search query language" 

`https://github.com/search?q=user:$USERNAME+language:$LANGUAGE`

* `$LANGUAGE` is replaced with `ruby`, `javascript` ...
* `$USERNAME` is replaced with the username, `paul`, `tenderlove` ...

There is also a lot of different params, to filter, sort.

**If you guys found the idea interesting, I would be happy to open a pull request**

**Comment by vdaubry** [comment]
I like this idea, using github search is clever.
Thanks a lot for offering to open a PR.

**Comment by marceloboeira** [comment]
@vdaubry thanks, I'll work on the pr asap :dancers:

**Comment by vdaubry** [comment]
It's done, thanks to @nunogoncalves !

**Comment by marceloboeira** [comment]
@vdaubry / @nunogoncalves awesome! 😎
