### ISSUE TITLE
Removed users appear to be back

### ISSUE THREAD

**Issue by jwise** [vdaubry/github-awards#69]
It looks like I am back, against my requests.  In #9 I was removed from the ranking, but today I got a recruiter sending me mail, because they found me on GitHub Awards.

May I be removed again?

(Adding as well @tdfischer, @skimbrel, @asmallteapot, and @n1k0, who asked for the same in #9.)

**Comment by skimbrel** [comment]
+1. Not only that, but my name and face appear right above an ad claiming "Affiliated with" in a way that makes it unclear whether the site or I am affiliated.

**Comment by n1k0** [comment]
Thanks for the heads up @jwise. Please remove my profile from this website.

**Comment by jwise** [comment]
Oh yeah, that's *really* bad.  I am absolutely not affiliated with loggly.  Yes, this needs to go.  Thanks.

**Comment by vdaubry** [comment]
I had manually removed your profiles but they got imported again when i added the daily import from Github-Archive.

This is definitely a bug, i'm going to remove your profiles from the ranking and add a blacklist so that this doesn't happen again.

I'll let you know as soon as it's done. I apologize for the inconvenience.

**Comment by vdaubry** [comment]
Hi everyone, 

I removed the following profiles from Github Awards :  
@jwise
@tdfischer
@skimbrel
@asmallteapot
@n1k0

I also added a blacklist of profile that should be ignored from GithubArchive events.
All the previous profile are added to the blacklist :

> BlacklistedUser.select(:username).map(&:username)
> BlacklistedUser Load (0.5ms)  SELECT "blacklisted_users"."username" FROM
> "blacklisted_users"
> => ["jwise", "skimbrel", "tdfischer", "asmallteapot", "n1k0"]

This should prevent your profiles from re-appearing on Github Awards.

I'm closing this issue, feel free to re-open it if you have any more questions.
