### ISSUE TITLE
Profile Edits

### ISSUE THREAD

**Issue by ming13** [vdaubry/github-awards#7]
Are profiles refreshed after editing? Is there any way to trigger this? Fixed my GitHub location information, but still getting “we couldn’t find your city from your location”.

**Comment by moneypenny** [comment]
Same here. It interpreted "Kentucky" as "Australia", so I updated my Github profile to include city + state. Still shows Australia on github-awards, though.

**Comment by lupidan** [comment]
My city is not being recognized for some reason, but a friend has the same city as me, and it is recognized correctly. :(
I also tried editing with the format "City, Country", but I am getting the same results

**Comment by proofit404** [comment]
+1 for this fix

**Comment by ecnalyr** [comment]
Has anyone found a way to reliably replicate this?

**Comment by vdaubry** [comment]
I'm working on adding github connect + refresh button.

Untill then i manually updated your profiles and will update the ranking today !

**Comment by Newbilius** [comment]
Can you update my location too?) I change it many month ago, but still have "We couldn't find your city from your location on GitHub :( ".

**Comment by vdaubry** [comment]
@Newbilius Did you try to update your profile with the refresh button under your avatar ?

**Comment by Newbilius** [comment]
Sorry, i don't notice is first time :-( Now all just fine!

**Comment by BrandConstantin** [comment]
Hello
I refreshed the profile several time, but it's not working.
All its started when given authorization to the freecodecamp.com to access my GitHub.
You can look my profile, BrandConstantin, please!
