### ISSUE TITLE
"We couldn't find your city from your location on GitHub :("

### ISSUE THREAD

**Issue by leekchan** [vdaubry/github-awards#73]
Hi.

I've tried refresh my profile several times (by clicking the refresh button below my avatar), but my location information is not updated.

Could you check my profile?

username : leekchan

Thanks.

**Comment by vdaubry** [comment]
Did you try to refresh your profile ? It's the green button under your avatar.

**Comment by leekchan** [comment]
Yes. I clicked the green button.

![image](https://cloud.githubusercontent.com/assets/823358/10657473/f093b25c-78c6-11e5-85fb-10be7d78c5d3.png)

The page said "your data is updating", but nothing happened.

![image](https://cloud.githubusercontent.com/assets/823358/10657480/128c2e16-78c7-11e5-9f18-db297e2abf19.png)

**Comment by vdaubry** [comment]
ok thx, i'm looking into this

**Comment by vdaubry** [comment]
@leekchan : the backgound worker was down. Can you check again ?

**Comment by leekchan** [comment]
Thanks :)

**Comment by rajdee** [comment]
It's back again. And yes,  I've tried refresh my profile several times.
user: rajdee

**Comment by BrandConstantin** [comment]
Hello
I refreshed the profile several time, but it's not working.
All its started when given authorization to the freecodecamp.com to acces my GitHub.
You can look my perfile, BrandConstantin, please!
