### ISSUE TITLE
Only code?

### ISSUE THREAD

**Issue by tatica** [vdaubry/github-awards#78]
Hey! I just check the app and it's quite fun, however, all my contributions are translations and sadly I can't have the same fun as my friends. Would it be able to also count the amount of translated strings?

Thx!

**Comment by vdaubry** [comment]
Hi !
GitHub Awards counts the number of stars from your repo. You could create a repository with some of your work, if people star it you will climb up in the ranking.

I'm closing this issue, good luck with your projects.
