### ISSUE TITLE
Only a few people are showing up on site

### ISSUE THREAD

**Issue by whackashoe** [vdaubry/github-awards#81]
I'm now the only person in my city whereas there used to be 20 or so. For worldwide there is small fraction of prior amount of people.

**Comment by antinucleon** [comment]
Yes, a lot of record are missing.

**Comment by vdaubry** [comment]
The ranking was re-building, it should be done now. Can you check if it's ok for you ?

**Comment by whackashoe** [comment]
There are less than half of prior users for javascript at least which I remember used to be ~595k, now when checked world total is ~231k.

**Comment by vdaubry** [comment]
@whackashoe : users with less than 1 start were still computing, it's ok now.

**Comment by marceloboeira** [comment]
@whackashoe @vdaubry I guess is messed up again....

<img width="1197" alt="screenshot 2015-11-15 09 28 47" src="https://cloud.githubusercontent.com/assets/1898225/11168568/59f9094c-8b7b-11e5-82ad-374df7286c4f.png">

**Comment by vdaubry** [comment]
yep, there's definitely an issue with Redis... I'm looking into it asap
Thanks for raising this

**Comment by vdaubry** [comment]
I restarted the redis server using the previous snapshot, rankings are back. I'm monitoring the situation
Let me know if you notice something's wrong.

**Comment by marceloboeira** [comment]
@vdaubry alright :+1:
