### ISSUE TITLE
Location not updating

### ISSUE THREAD

**Issue by Tibolte** [vdaubry/github-awards#84]
I recently changed my location from Reykjavík to Paris. However I still see myself ranked in Reykjavík and Iceland. Is it gonna refresh soon or is it not supported?

**Comment by vdaubry** [comment]
GitHub Awards updates hourly based on data from [GitHub Archive](https://www.githubarchive.org/)

You can force a refresh for your profile with the refresh button under your avatar.

I'm closing this issue, let me know if you have troubles updating your profile.

**Comment by Tibolte** [comment]
works :+1: I didn't know about that refresh profile thing. Keep up the good work :)
