### ISSUE TITLE
why it show : We couldn't find your city from your location on GitHub :(

### ISSUE THREAD

**Issue by zhuangtongfa** [vdaubry/github-awards#86]
http://github-awards.com/users/search?login=zhuangtongfa
my github:
https://github.com/zhuangtongfa

**Comment by vdaubry** [comment]
did you try to refresh your profile ? (green button under your avatar)

**Comment by zhuangtongfa** [comment]
yes,but it still show couldn't findcity from location on GitHub

**Comment by vdaubry** [comment]
I updated your profile.

**Comment by Fatima-Usf** [comment]
I have same problem
