### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by TheFinestArtist** [vdaubry/github-awards#88]
Fork count is usually proportional to star count, but some repo shows higher proportion between fork count and star count than others. 

To compare with Facebook post, starring a repo is similar with liking a post and forking a repo is similar with saving a post for later use. Therefore, I think fork count is more valuable number to judge how popular each repo is than star count.

**Comment by vdaubry** [comment]
Thanks for your input but we don't have any plan to take forks into account at the moment.
I'm closing this issue.
