### ISSUE TITLE
Missing ranks

### ISSUE THREAD

**Issue by vlad-saling** [vdaubry/github-awards#89]
Some of the language+location combinations in rank search return weird results. Examples:

http://github-awards.com/users?utf8=%E2%9C%93&type=city&language=ActionScript&city=Slovakia
On the date this issue was created it threw ranks null, 1, 2, null.

http://github-awards.com/users?utf8=%E2%9C%93&type=city&language=PHP&city=Slovakia
On the date this issue was created it threw ranks null, 1, ....

http://github-awards.com/users?utf8=%E2%9C%93&type=country&language=JavaScript&country=Budapest
On the date this issue was created it missed rank 1, 3, 6 and more.

Btw, I really like the project :)

**Comment by vdaubry** [comment]
@vlad-saling : Thanks for reporting.
I'm looking into this and let you know when i have more info.

**Comment by techfort** [comment]
@vdaubry don't know if this is the same issue, but if you go here http://github-awards.com/users?city=cork&language=JavaScript&type=city i am apparently the only js developer in Cork, Ireland (believe me, I'm not :D ) , there used to be loads up until yesterday.

**Comment by vdaubry** [comment]
It's fixed (for now), see #96

**Comment by vlad-saling** [comment]
Cool! Thnx. Sharing your https://github.com/vdaubry/github-awards/issues/96 !
