### ISSUE TITLE
Remove profiles

### ISSUE THREAD

**Issue by jwise** [vdaubry/github-awards#9]
Users must be able to remove themselves from all ranking.

Here are some reasons why a user may prefer not to be listed.
* For instance, a user may prefer not to be listed in a list of users in their city (the information is publicly accessible, but they would prefer not to be aggregated).
* A user may have other privacy concerns, not just of their location
* A user may believe that ranking is not productive, and hence would prefer not to be used to rank other developers.

(Personally, I subscribe to the third, but I can imagine others who might subscribe to 1 or 2.)

So, minimally, please remove me from all ranking -- and, ideally, add functionality so that others can do the same for themselves.

Thanks,
joshua

**Comment by jwise** [comment]
One argument, by the way, is that ranking should be opt-in.  This is how GitHub Resume (https://github.com/resume/resume.github.com) does it.

**Comment by tdfischer** [comment]
:+1: for opting in. I'm not one to be used to rank others.

**Comment by skimbrel** [comment]
I'd like out as well.

**Comment by asmallteapot** [comment]
:+1:

**Comment by n1k0** [comment]
Same.

**Comment by vdaubry** [comment]
I'll remove your accounts, all your data will be suppressed from the ranking computation and personal informations removed from the database. I'll update you when it's done.

**Comment by jwise** [comment]
Thanks @vdaubry! I appreciate it!

**Comment by vdaubry** [comment]
Ok all your accounts have been removed. I'll update the ranking today
