### ISSUE TITLE
[Feature Request] exclude organizations from ranks

### ISSUE THREAD

**Issue by techfort** [vdaubry/github-awards#97]
Hi - great job on github-awards, i hope you resolve the hosting issue.

I find it strange to have organizations in the same rank as single users. I wouldn't include organizations in the ranks at all, especially if you implement the feature that ranks a user's contributions to repos not owned by the user.
Putting an organization with multiple users in the same rank as a single user seems incoherent.

**Comment by vdaubry** [comment]
Thanks, i agree with you that having 2 different rankings would be a nice feature.
PR are welcome.

I'm closing this issue.
